version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - serve
      - --debug
      - --pretty
      - --dev
      - --jwt-secretkey
      - mysupersecretkey
      # - --oidc=false # uncomment to bypass auth checks
      - --fga-host
      - openfga:8080
      - --fga-scheme
      - "http"
    ports:
      - "17608:17608"
    restart: unless-stopped
    networks:
      - default
